apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
        - name: project1-container
          image: psreelakshmi143/project1:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: project1-service
spec:
  type: NodePort
  selector:
    app: project1
  ports:
    - port: 3000        # Port inside cluster
      targetPort: 3000  # Container port
      nodePort: 30080   # Port on host/node
